import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import AppHeader from "@/src/components/AppHeader/AppHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Pokemons App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen bg-gray-700 select-none">
          <AppHeader />
          <main className="flex flex-col items-center justify-between pt-12 pb-12">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
